# Generated by Django 5.0.3 on 2026-01-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='engagement_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='reputation_score',
            field=models.FloatField(default=0),
        ),
    ]
