# Generated by Django 5.0.3 on 2026-01-13 19:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_ai_score_profile_engagement_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communitypostlike',
            unique_together={('user', 'post')},
        ),

        # Use ALTER ... ADD COLUMN IF NOT EXISTS for DB-safe adds
        migrations.RunSQL(
            sql=(
                "ALTER TABLE core_commentlike "
                "ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();"
            ),
            reverse_sql="ALTER TABLE core_commentlike DROP COLUMN IF EXISTS created_at;",
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE core_communitypostlike "
                "ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();"
            ),
            reverse_sql="ALTER TABLE core_communitypostlike DROP COLUMN IF EXISTS created_at;",
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE core_profile "
                "ADD COLUMN IF NOT EXISTS action_points integer NOT NULL DEFAULT 0;"
            ),
            reverse_sql="ALTER TABLE core_profile DROP COLUMN IF EXISTS action_points;",
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE core_profile "
                "ADD COLUMN IF NOT EXISTS badge varchar(32) NOT NULL DEFAULT 'Novice';"
            ),
            reverse_sql="ALTER TABLE core_profile DROP COLUMN IF EXISTS badge;",
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE core_profile "
                "ADD COLUMN IF NOT EXISTS last_recalc timestamptz NULL;"
            ),
            reverse_sql="ALTER TABLE core_profile DROP COLUMN IF EXISTS last_recalc;",
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE core_profile "
                "ADD COLUMN IF NOT EXISTS score smallint NOT NULL DEFAULT 0;"
            ),
            reverse_sql="ALTER TABLE core_profile DROP COLUMN IF EXISTS score;",
        ),

        # keep the remaining alterations (they are safe to run)
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.post'),
        ),
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communitycomment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='communitycomment',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.post'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/default.png', null=True, upload_to='profile_photos/'),
        ),
    ]
