# Generated by Django 6.0.1 on 2026-01-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_communitypostlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycomment',
            name='text',
            field=models.TextField(),
        ),
    ]
