# Generated by Django 6.0.1 on 2026-01-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_ai_score_profile_engagement_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reputation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/default.png', upload_to='profile_photos/'),
        ),
    ]
