# Generated by Django 6.0.1 on 2026-01-12 17:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_communitycomment_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communitypostlike',
            unique_together={('user', 'post')},
        ),
        migrations.RemoveField(
            model_name='communitypostlike',
            name='created_at',
        ),
    ]
