# Generated by Django 6.0.1 on 2026-01-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_reputation_score_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='action_points',
            field=models.IntegerField(default=0),
        ),
    ]
