# Generated by Django 6.0.1 on 2026-01-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_action_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badge',
            field=models.CharField(default='Newbie', max_length=50),
        ),
    ]
