# Generated by Django 6.0.1 on 2026-01-12 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_communitypostlike_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='communitypostlike',
            unique_together={('post', 'user')},
        ),
    ]
